import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../../components/header'
import './styles/master.scss'
import './styles/all.min.css'
import './styles/bootstrap.min.css'
import React from 'react'
import './styles/locomotive-scroll.min.css'
import './styles/master-dist.css'
//import './styles/master.css.map'
import './styles/meanmenu.min.css'
import './styles/progressbar.css'
import './styles/swiper-bundle.min.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
